spring.application.name=MicroServicioPlaza

spring.datasource.url=jdbc:mysql://localhost:3306/Plaza
spring.datasource.username=root
spring.datasource.password=JOSE1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.mongodb.uri=mongodb://localhost:27017/Trazabilidad
spring.data.mongodb.database=Trazabilidad

jwt.secret=c29tZVNlY3JldEtleVRoYXRJc0xvbmdFbm91Z2hGb3JIZW1h
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.jpa.hibernate.ddl-auto=update

server.port=8082
usuario.service.url=http://localhost:8081