spring.application.name=MicroServicioPlaza

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.mongodb.uri=mongodb://localhost:27017/Trazabilidad
spring.data.mongodb.database=Trazabilidad

jwt.secret=c29tZVNlY3JldEtleVRoYXRJc0xvbmdFbm91Z2hGb3JIZW1h

spring.jpa.hibernate.ddl-auto=update

server.port=8082
usuario.service.url=http://localhost:8081
mensajeria.service.url=http://localhost:8083

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.writer-with-default-pretty-printer=true